### ISSUE TITLE
App doesn't run on simulator

### ISSUE THREAD

**Issue by JRG-Developer** [JeffBNimble/LoLBookOfChampions-ios-sqlite#6]
@JeffBNimble, thank you for this excellent example app.

I've been trying to get it to run on the simulator using Xcode 6.3.2 (latest released version as of this writing), yet I consistently receive this error dialogue:

"Invalid or missing Program/ProgramArguments"

Is this a known issue? Can you recommend a workaround or possible culprit?

**Comment by JeffBNimble** [comment]
@JRG-Developer, thank you for the nice comments. Yes, this is a known issue and yes there is a workaround. If you (or anyone) knows a solution, feel free to create a pull request or reply to this and let me know how to resolve permanently.

The issue is that the scheme to run the app in the simulator is pointing to an invalid location. To fix this, you'll need to edit the scheme. In the Run configuration, drop down the "Executable" and select "Other...". This will open a Finder window. Navigate to your Library/Developer/DerivedData/LoLBookOfChampions.../Build/Products/Debug-iphonesimulator folder and select the LoLBookOfChampions.app. I have no idea why this is wrong and would love a solution. This will work for you as I have to do this frequently. Sorry for the inconvenience.

![screenshot_6_25_15__1_20_pm](https://cloud.githubusercontent.com/assets/732717/8362198/1d39f2ae-1b3d-11e5-9d09-9473955b5662.jpg)

**Comment by JRG-Developer** [comment]
I noticed that the app target _wasn't_ added to the _Products_ group, which got me thinking that a build path perhaps was corrupted with the app target? (Perhaps, at some point, you deleted the .app product from the _Products_ group and this caused a problem...?)

Interestingly, simply by duplicating the app target, the copy runs on the simulator without problems! :)

I'm going to see if I can track down the path issue...? Otherwise, a simple way to fix this may be duplicating the app target and test targets, setting up a relationship between them within scheme editor, and cleaning up each to use the original ~info.plist files and deleting the copies of such.

**Comment by JRG-Developer** [comment]
I'm closing the issue in lieu of pull request #7.

This pull request _only_ includes duplicating the app and test target. It appears there are several issues with the unit tests, however, which currently do not build.
